spring:
  datasource:
    url: jdbc:mysql://101.201.101.181:3306/xin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml  #对应mapper映射xml文件所在路径
  type-aliases-package: com.water.water.pojo  #对应实体类路径
server:
  port: 8443
